plugins {
    id 'java'
}

description = 'Support for datatypes of nostr-proto library'

dependencies {
    implementation project(':nostr-proto-json')

    implementation "tools.jackson.core:jackson-databind:${rootProject.ext.jackson3Version}"

    testImplementation "tools.jackson.jr:jackson-jr-all:${rootProject.ext.jacksonJr3Version}"

    testImplementation("io.github.theborakompanioni:nostr-core:${rootProject.ext.nostrSpringBootStarterVersion}") {
        exclude group: 'io.github.theborakompanioni', module: 'nostr-proto'
        exclude group: 'io.github.theborakompanioni', module: 'nostr-proto-json'
    }
    testImplementation("io.github.theborakompanioni:nostr-identity:${rootProject.ext.nostrSpringBootStarterVersion}") {
        exclude group: 'io.github.theborakompanioni', module: 'nostr-proto'
        exclude group: 'io.github.theborakompanioni', module: 'nostr-proto-json'
    }
}
